import { getSupabaseBrowserClient } from '@/lib/supabase';

export interface WatermarkConfig {
  text: string;
  fontSize: number;
  color: string;
  opacity: number;
  position: 'center' | 'corner' | 'diagonal';
  repeat: boolean;
}

export const DEFAULT_WATERMARK: WatermarkConfig = {
  text: 'SaviEduTech',
  fontSize: 48,
  color: 'rgba(99, 102, 241, 0.15)',
  opacity: 0.15,
  position: 'center',
  repeat: true,
};

export function generateWatermarkSVG(config: WatermarkConfig = DEFAULT_WATERMARK): string {
  const { text, fontSize, color, position, repeat } = config;
  
  if (repeat) {
    return `
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
        <defs>
          <pattern id="watermark-pattern" x="0" y="0" width="300" height="200" patternUnits="userSpaceOnUse">
            <text x="150" y="100" 
                  font-family="Arial, sans-serif" 
                  font-size="${fontSize}" 
                  fill="${color}"
                  text-anchor="middle" 
                  dominant-baseline="middle"
                  transform="rotate(-45, 150, 100)">
              ${text}
            </text>
          </pattern>
        </defs>
        <rect width="100%" height="100%" fill="url(#watermark-pattern)" />
      </svg>
    `.trim();
  }
  
  const positions: Record<string, string> = {
    center: 'x="50%" y="50%"',
    corner: 'x="90%" y="90%"',
  };
  
  return `
    <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
      <text ${positions[position]}
            font-family="Arial, sans-serif" 
            font-size="${fontSize}" 
            fill="${color}"
            text-anchor="middle" 
            dominant-baseline="middle">
        ${text}
      </text>
    </svg>
  `.trim();
}

export function addWatermarkToHTML(content: string, config: WatermarkConfig = DEFAULT_WATERMARK): string {
  const watermarkSVG = generateWatermarkSVG(config);
  const encodedSVG = encodeURIComponent(watermarkSVG);
  
  return `
    <div style="position: relative; min-height: 100vh;">
      <div style="position: absolute; top: 0; left: 0; right: 0; bottom: 0; pointer-events: none; z-index: 1;">
        <img src="data:image/svg+xml;${encodedSVG}" style="width: 100%; height: 100%; object-fit: cover;" alt="watermark" />
      </div>
      <div style="position: relative; z-index: 2;">
        ${content}
      </div>
    </div>
  `;
}

export function addWatermarkToPDF(content: string, config: WatermarkConfig = DEFAULT_WATERMARK): string {
  const watermarkSVG = generateWatermarkSVG(config);
  const encodedSVG = encodeURIComponent(watermarkSVG);
  
  return `
    <div style="position: relative;">
      <img src="data:image/svg+xml;${encodedSVG}" 
           style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; opacity: ${config.opacity}; pointer-events: none;" 
           alt="watermark" />
      <div style="position: relative; z-index: 1;">
        ${content}
      </div>
    </div>
  `;
}

export async function saveWatermarkedPDF(
  htmlContent: string,
  fileName: string,
  config: WatermarkConfig = DEFAULT_WATERMARK
): Promise<{ url: string; path: string }> {
  const supabase = getSupabaseBrowserClient();
  
  const watermarkedHTML = addWatermarkToPDF(htmlContent, config);
  
  const blob = new Blob([watermarkedHTML], { type: 'text/html' });
  const filePath = `journals/${Date.now()}-${fileName}`;
  
  const { data, error } = await supabase.storage
    .from('journals')
    .upload(filePath, blob, {
      contentType: 'text/html',
      upsert: true,
    });
  
  if (error) throw error;
  
  const { data: urlData } = supabase.storage
    .from('journals')
    .getPublicUrl(filePath);
  
  return { url: urlData.publicUrl, path: filePath };
}

export function generateAIDocumentHeader(
  title: string,
  subject: string,
  classLevel: string
): string {
  return `
    <div style="margin-bottom: 20px; padding-bottom: 20px; border-bottom: 2px solid #6366f1;">
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <div>
          <h1 style="margin: 0; color: #1f2937; font-size: 24px;">${title}</h1>
          <p style="margin: 5px 0 0; color: #6b7280; font-size: 14px;">
            ${subject} • ${classLevel} • Generated by SaviEduTech AI
          </p>
        </div>
        <div style="text-align: right;">
          <span style="display: inline-block; padding: 4px 12px; background: #6366f1; color: white; border-radius: 4px; font-size: 12px;">
            AI GENERATED
          </span>
          <p style="margin: 5px 0 0; color: #9ca3af; font-size: 11px;">
            ${new Date().toLocaleDateString('en-IN', { 
              day: 'numeric', 
              month: 'long', 
              year: 'numeric' 
            })}
          </p>
        </div>
      </div>
    </div>
  `;
}

export function generateAIDocumentFooter(): string {
  return `
    <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 11px;">
      <p style="margin: 0;">
        Generated by SaviEduTech AI • www.saviedtech.com • info@saviedtech.com
      </p>
      <p style="margin: 5px 0 0;">
        This document is AI-generated and may contain errors. Please verify before use.
      </p>
    </div>
  `;
}

export function wrapWithWatermark(
  content: string,
  options?: {
    title?: string;
    subject?: string;
    classLevel?: string;
    config?: WatermarkConfig;
  }
): string {
  const { title, subject, classLevel, config } = options || {};
  
  let wrappedContent = content;
  
  if (title || subject || classLevel) {
    wrappedContent = generateAIDocumentHeader(
      title || 'AI Generated Document',
      subject || 'General',
      classLevel || 'All Classes'
    ) + wrappedContent;
  }
  
  wrappedContent += generateAIDocumentFooter();
  
  return addWatermarkToHTML(wrappedContent, config);
}
